name: cera-2019
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pandas==0.25.3
  - jupyterlab==1.2.3
  - altair==3.2.0
  - vega==2.6.0
  - vega_datasets==0.7.0
  - pip==19.3.1
  - pip:
    - xlrd==1.2.0
